### ISSUE TITLE
Rename collection migration introduces inconsistent migration record state error.

### ISSUE THREAD

**Issue by MatejJan** [peerlibrary/meteor-peerdb-migrations#2]
I have 3 migrations added to the `Submission` Document:

```
#1
class Migration extends Document.PatchMigration
  name: "Reprocess images of the submission."

#2
Submission.renameCollectionMigration 'PixelArtAcademyPixelDailiesSubmissions', 'PixelArtDatabase.PixelDailies.Submissions'

#3
class Migration extends Document.PatchMigration
  name: "Convert image URLs to https."
```

After adding migration #3 to the project, running the server outputs the error:

> Error: Incosistent migration record state, missing migrationName='Reprocess images of the submission.', oldCollectionName='PixelArtDatabase.PixelDailies.Submissions', newCollectionName='PixelArtDatabase.PixelDailies.Submissions', oldVersion='1.0.0', newVersion='1.0.1'

Database state of the relevant migrations is:
![](http://i.imgur.com/G1sUReP.png)

When trying to debug, I manually changed the Migration document (serial 2) to include the dots like the error requested, but then the error was:

> Error: Incosistent migration recorded, expected migrationName='Reprocess images of the submission.', oldCollectionName='PixelArtAcademyPixelDailiesSubmissions', newCollectionName='PixelArtAcademyPixelDailiesSubmissions', oldVersion='1.0.0', newVersion='1.0.1', got: { _id: 'PF3DzZc8DyKfeS6Lf',
> serial: 3,
> migrationName: 'Renaming collection from \'PixelArtAcademyPixelDailiesSubmissions\' to \'PixelArtDatabase.PixelDailies.Submissions\'',
> oldCollectionName: 'PixelArtAcademyPixelDailiesSubmissions',
> newCollectionName: 'PixelArtDatabase.PixelDailies.Submissions',
> oldVersion: '1.0.1',
> newVersion: '2.0.0',

Removing all migration documents from the DB, so that they were recreated, solved the issue.

**Comment by MatejJan** [comment]
I forgot that I opened this issue already, as I ran into this problem again today. Except this time I went over the library code and found where the problem lies.

The situation is that the first two migrations (`#1` and `#2`) are already in the database. When the third one gets analyzed (in the first loop over all migrations), this code runs:

```
else if migrationsPending is Number.POSITIVE_INFINITY
      # This is the collection name recorded as the last, so we start with it
      initialName = currentName
      migrationsPending = i
```

So it didn't find the third one in the database, and sets it correctly as the first pending migration. But it also sets `initialName` to `currentName`, which—since `#2`just ran—is `PixelArtDatabase.PixelDailies.Submissions`.

Now when migrations are actually applied (second loop over migrations), `initialName` has incorrect value of the name at first pending migration. Therefore, when it tries to find `#1` in the database, it tries to fetch it with the latest (post `#2` name):

```
if i < migrationsPending
      count = globals.Document.Migrations.update
        migrationName: migration.name
        oldCollectionName: currentName
        newCollectionName: newName
        oldVersion: currentSchema
        newVersion: newSchema
      ,
```

It can't find it, so it throws an error.

I'm guessing you need to remember `currentName` when finding the first pending document, to know what the collection is currently called in the database. What I don't understand is why store this in `initialName`.

I also don't understand how the second loop works anyway if `initialName` is actually the first known name of the collection. How does this work:

```
counts = migration.forward @, new DirectCollection(currentName), currentSchema, newSchema
```

when `currentName` starts out with `initialName` that is not how the collection is named currently in the database? 

So because I don't understand this bit, I also can't give any suggestion of where the fix might lie. I'd imagine there should be a separate variable, something like `currentDatabaseName` and that one is set to the name of the first pending migration. Then you use that when constructing `DirectCollection`, and only update `currentDatabaseName` when rename migrations get added (and they were pending). But I'm probably missing something.

**Comment by mitar** [comment]
Care to make a PR with improved test which triggers this error?

**Comment by MatejJan** [comment]
One extra thing to note is that my workaround (deleting all migrations to force re-creation) doesn't create any different migration documents in the database (apart from different serial numbers), but works because all the migrations become pending and all renaming migrations are applied in one go. It's just this mix of existing and pending migrations that triggers the problem. Well, I guess that's exactly what I figured out above by analyzing the source code. 

I'll look into making a PR, if I understand how to make a test. :)

**Comment by mitar** [comment]
See here: https://github.com/peerlibrary/meteor-peerdb-migrations/blob/master/tests_migrations.coffee

**Comment by mitar** [comment]
You can run them by being in the repo an running `meteor test-packages ./` and opening `localhost:3000` in your browser.

**Comment by MatejJan** [comment]
Yeah, I was just going over this source code. However, since I haven't really done tests before, I might be over my head at the current moment to go and see if I can figure it out (or maybe it's really easy and I'm just overreacting).

I think my comment above complicates the test a bit. What should happen would be:
1. Start the server with only migration `#1` and `#2` added.
1. Run migrations so that the two migrations get added to the database.
1. Add migration `#3` as well. Start the server again.

At this point the test is expected to fail with the current code. But this running server twice (or dynamically adding the third migration in the middle) scares me a bit.
