### ISSUE TITLE
Missing collection error has different text on latest Meteor, breaks renameCollectionMigration

### ISSUE THREAD

**Issue by MatejJan** [peerlibrary/meteor-peerdb-migrations#3]
When updating to latest Meteor, Mongo started reporting a missing collection with a different text than before. When trying to rename a collection, we now get:
> `MongoError: Source collection <name here> does not exist`

The line in question is:
https://github.com/peerlibrary/meteor-peerdb-migrations/blob/6494e22ab37082612c27188978065da46778719e/server.coffee#L335

And needs to be updated to:
```
throw error unless /Source collection .* does not exist/.test "#{error}"
```

**Comment by mitar** [comment]
Published as peerlibrary:peerdb-migrations@1.1.1. Thanks for the report and suggested fix.
